name: Publish Extent Report

on:
  workflow_run: 
    workflows: ["Data Driven Framework"]
    types:
      - completed
    branches:
      - publishreports

permissions:
  contents: read
  pages: write
  id-token: write

jobs:

  publish:

    if: ${{ github.event.workflow_run.conclusion != 'cancelled' }}

    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:

      - name: Download Report Artifact
        uses: dawidd6/action-download-artifact@v9
        with:
          run_id: ${{ github.event.workflow_run.id }}
          workflow_conclusion: success
          name: Test-Reports
          path: reports

      - name: Find latest report
        run: |
          latest=$(find reports -name "*.html" | sort | tail -1)
          cp "$latest" reports/index.html

      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: reports

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4